language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - py.test # or py.test for Python versions 3.5 and below
# command to configure build notifications
notifications:
  email: false
# command to configure travis for recent git builds
git:
  depth: 3
# command to configure services
services: mongodb

