language: python
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
# command to configure build notifications
notifications:
  email: false
# command to configure travis for recent git builds
git:
  depth: 3
# command to configure services
services: mongodb

